name: trackncheck
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_database: ^11.3.9
  flutter_easyloading: ^3.0.5
  lottie: ^2.7.0
  permission_handler: ^12.0.1
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  mobile_scanner: ^7.0.1
  http: ^1.4.0
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^15.2.10
  timezone: ^0.10.1
  workmanager: ^0.9.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1   # <-- Added for app icon

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

# App Icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app-icon.png"   # <-- Place your icon here
  adaptive_icon_background: "#ffffff"        # <-- Background color (Android adaptive)
  adaptive_icon_foreground: "assets/icon/app-icon.png"
