// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvCf0cOj6HnzLDWo7XiUsAWEcgsct5CV8',
    appId: '1:947913333322:web:e03951de07f526f1e4e4b3',
    messagingSenderId: '947913333322',
    projectId: 'trackncheck-c6b75',
    authDomain: 'trackncheck-c6b75.firebaseapp.com',
    storageBucket: 'trackncheck-c6b75.firebasestorage.app',
    measurementId: 'G-L0NWC4G2BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmoLDeSFVPBCR4kZfeyeSuK_-s8r-Bhx8',
    appId: '1:947913333322:android:3f36cf5cde8bb133e4e4b3',
    messagingSenderId: '947913333322',
    projectId: 'trackncheck-c6b75',
    storageBucket: 'trackncheck-c6b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwliJ95vfRr5gtXT6XbyV3YZpLY0H7WHk',
    appId: '1:947913333322:ios:93cc3a40143b9d96e4e4b3',
    messagingSenderId: '947913333322',
    projectId: 'trackncheck-c6b75',
    storageBucket: 'trackncheck-c6b75.firebasestorage.app',
    iosBundleId: 'com.example.trackncheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwliJ95vfRr5gtXT6XbyV3YZpLY0H7WHk',
    appId: '1:947913333322:ios:93cc3a40143b9d96e4e4b3',
    messagingSenderId: '947913333322',
    projectId: 'trackncheck-c6b75',
    storageBucket: 'trackncheck-c6b75.firebasestorage.app',
    iosBundleId: 'com.example.trackncheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvCf0cOj6HnzLDWo7XiUsAWEcgsct5CV8',
    appId: '1:947913333322:web:ad87a78ada2c82ffe4e4b3',
    messagingSenderId: '947913333322',
    projectId: 'trackncheck-c6b75',
    authDomain: 'trackncheck-c6b75.firebaseapp.com',
    storageBucket: 'trackncheck-c6b75.firebasestorage.app',
    measurementId: 'G-HYRF7LQDT8',
  );
}
